### ISSUE TITLE
Add note to uncomment certain configs if editing Score Client application.properties

### ISSUE THREAD

**Issue by b-f-chan** [icgc-dcc/dcc-docs#49]
When installing Score Client, some lines in the application.properties file may need to be uncommented.

Current documentation does not make this clear and new users may forget/neglect to do this and run into errors.

Specifically:

* accessToken - Need to uncomment to run
* transport.parallel, transport.memory - Need to uncomment if tweaking data transfer params

Doc link:
https://docs.icgc.org/download/guide/#access-configuration

As reported by @alekspejovic

**Comment by alekspejovic** [comment]
Issue fixed in prod.
