### ISSUE TITLE
ICGC docs vertical scroll freezes sometimes

### ISSUE THREAD

**Issue by b-f-chan** [icgc-dcc/dcc-docs#53]
**Issue:**

* On the ICGC docs site, sometimes when reading content, the vertical scroll freezes / gets stuck.
* To get unstuck, they must click an entirely different section in the left menu-bar.
* This is an annoying experience for the end user / reader.
* Confirmed issue on Chrome, Firefox; testing on MS Edge pending
* Root cause unclear; requires investigation.

**Requested Fix:**

* Fix the scroll so that readers can scroll down per normal as they browse the content.

**Screenshots:**

* Frozen vertical scroll:

**Comment by rosibaj** [comment]
Closing this as new feature devlopment will focus on ARGO - site is still functional!
